# Generated by Django 3.1.3 on 2023-12-07 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_tile', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('software_developer', 'Software Developer'), ('software_engineer', 'Software Engineer'), ('junior_software_developer', 'Junior Software Developer'), ('junior_software_engineer', 'Junior Software Engineer')], default='software_developer', max_length=50)),
                ('manager', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTelephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(default='', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsm_app.staff')),
            ],
        ),
    ]
