# Generated by Django 3.1.3 on 2023-12-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(default='', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('priority', models.CharField(choices=[('highest', 'Highest'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('lowest', 'Lowest')], default='medium', max_length=10, null=True)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_development', 'In Development'), ('on_hold', 'On Hold'), ('done', 'Done'), ('reject', 'Reject')], default='to_do', max_length=50, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=30)),
                ('last_name', models.CharField(default='Bell', max_length=30)),
                ('dob', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('baseworker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tsm_app.baseworker')),
                ('role', models.CharField(choices=[('senior_software_developer', 'Senior Software Developer'), ('senior_software_engineer', 'Senior Software Engineer')], default='senior_software_developer', max_length=50)),
            ],
            bases=('tsm_app.baseworker',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('baseissue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tsm_app.baseissue')),
                ('project_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsm_app.leader')),
            ],
            bases=('tsm_app.baseissue',),
        ),
        migrations.CreateModel(
            name='WorkerTelephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=20, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsm_app.baseworker')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('baseworker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tsm_app.baseworker')),
                ('role', models.CharField(choices=[('software_developer', 'Software Developer'), ('software_engineer', 'Software Engineer'), ('junior_software_developer', 'Junior Software Developer'), ('junior_software_engineer', 'Junior Software Engineer')], default='software_developer', max_length=50)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsm_app.leader')),
            ],
            bases=('tsm_app.baseworker',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('baseissue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tsm_app.baseissue')),
                ('head_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsm_app.project')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsm_app.worker')),
            ],
            bases=('tsm_app.baseissue',),
        ),
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(to='tsm_app.Worker'),
        ),
    ]
