# Generated by Django 3.1.3 on 2023-12-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('highest', 'Highest'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('lowest', 'Lowest')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_development', 'In Development'), ('on_hold', 'On Hold'), ('done', 'Done'), ('reject', 'Reject')], default='to_do', max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('staffs', models.ManyToManyField(to='tsm_app.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('highest', 'Highest'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('lowest', 'Lowest')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_development', 'In Development'), ('on_hold', 'On Hold'), ('done', 'Done'), ('reject', 'Reject')], default='to_do', max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsm_app.project')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsm_app.staff')),
            ],
        ),
    ]
