# Generated by Django 3.1.3 on 2023-12-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm_app', '0002_project_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffTelephone',
            new_name='Telephone',
        ),
    ]
