# Generated by Django 3.1.3 on 2023-12-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm_app', '0003_auto_20231207_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='job_tile',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='manager',
        ),
        migrations.AddField(
            model_name='staff',
            name='team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
