# Generated by Django 3.1.3 on 2023-12-07 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tsm_app', '0004_auto_20231207_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='staffs',
        ),
        migrations.RemoveField(
            model_name='task',
            name='staff',
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('software_developer', 'Software Developer'), ('software_engineer', 'Software Engineer'), ('junior_software_developer', 'Junior Software Developer'), ('junior_software_engineer', 'Junior Software Engineer')], default='software_developer', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('software_developer', 'Software Developer'), ('software_engineer', 'Software Engineer'), ('junior_software_developer', 'Junior Software Developer'), ('junior_software_engineer', 'Junior Software Engineer')], default='software_developer', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tsm_app.leader'),
        ),
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(to='tsm_app.Worker'),
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tsm_app.worker'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsm_app.worker'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
